/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JOptionPane;
import Controller.Jogos;
import Controller.Jogos;

/**
 *
 * @author internet
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public MenuPrincipal() {
        initComponents();
        //getContentPane().setBackground(Color.blue);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGerarSorteios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        btnAnalisarResultados = new javax.swing.JButton();
        btnJogar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(380, 310));
        setPreferredSize(new java.awt.Dimension(400, 320));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGerarSorteios.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        btnGerarSorteios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/trevo-icone.png"))); // NOI18N
        btnGerarSorteios.setText("Gerar Sorteios");
        btnGerarSorteios.setMaximumSize(new java.awt.Dimension(190, 45));
        btnGerarSorteios.setMinimumSize(new java.awt.Dimension(190, 45));
        btnGerarSorteios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSorteiosActionPerformed(evt);
            }
        });
        getContentPane().add(btnGerarSorteios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 180, 100));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("Copyright © Vestindo Certo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 20));

        btnSair.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-fechar.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setMaximumSize(new java.awt.Dimension(190, 45));
        btnSair.setMinimumSize(new java.awt.Dimension(190, 45));
        btnSair.setPreferredSize(new java.awt.Dimension(190, 45));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 160, 180, 100));

        btnAnalisarResultados.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        btnAnalisarResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-ok.png"))); // NOI18N
        btnAnalisarResultados.setText("Resultados");
        btnAnalisarResultados.setMaximumSize(new java.awt.Dimension(190, 45));
        btnAnalisarResultados.setMinimumSize(new java.awt.Dimension(190, 45));
        btnAnalisarResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarResultadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnalisarResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 100));

        btnJogar.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        btnJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/jogar-icone.png"))); // NOI18N
        btnJogar.setText("Jogar");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJogar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 50, 180, 100));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("Escolha uma das opções abaixo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/mega-sena-background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarSorteiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSorteiosActionPerformed
        GerarSorteios gerarSoeteios = new GerarSorteios();
        gerarSoeteios.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGerarSorteiosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAnalisarResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarResultadosActionPerformed
        // TODO add your handling code here:
        Resultados resultados = new Resultados();
        resultados.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnAnalisarResultadosActionPerformed

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        // TODO add your handling code here:
        Jogar jogar = new Jogar();
        jogar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalisarResultados;
    private javax.swing.JButton btnGerarSorteios;
    private javax.swing.JButton btnJogar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
