/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ControllerRegistros;
import Controller.ControllerSorteios;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Ricardo Mota
 */
public class ViewResultados extends javax.swing.JFrame {

    public ViewResultados(){
        initComponents();
        int count = 0;
        String nome = "", jogo = "", resultadoFinal = "";
        List<ControllerRegistros> listaDeRegistros = new ArrayList<ControllerRegistros>();
        ControllerRegistros registros = new ControllerRegistros();
        listaDeRegistros = registros.getRegistros();
        
        for (ControllerRegistros registrosLocal : listaDeRegistros) {
            count++;
            nome = registrosLocal.getNome();
            jogo = (
                        registrosLocal.getDezena01() + " " + 
                        registrosLocal.getDezena02() + " " + 
                        registrosLocal.getDezena03() + " " + 
                        registrosLocal.getDezena04() + " " + 
                        registrosLocal.getDezena05() + " " + 
                        registrosLocal.getDezena06()
                    );
            resultadoFinal += "<b>" + nome + "</b> <blockquote>" + jogo + "</blockquote>";
            if(count == 3) break;
        }
        if (count > 0) {
            jLabelDadosDoBanco.setText("<html><body>"+resultadoFinal+"</body></html>");
        }else{
            jLabelDadosDoBanco.setText("<html><body>Você não tem nenhum jogo registrado.</body></html>");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelDadosDoBanco = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jButtonAnalisarJogos = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel1.setText("Resultados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabelDadosDoBanco.setBackground(new java.awt.Color(255, 0, 255));
        jLabelDadosDoBanco.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jLabelDadosDoBanco.setText("DADOS DO BANCO");
        getContentPane().add(jLabelDadosDoBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 380, 170));

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jLabel2.setText("Ultimos Jogos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButtonVoltar.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-voltar.png"))); // NOI18N
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 160, 60));

        jButtonAnalisarJogos.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jButtonAnalisarJogos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-ok.png"))); // NOI18N
        jButtonAnalisarJogos.setText("Analisar");
        jButtonAnalisarJogos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnalisarJogosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAnalisarJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 60));

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel8.setText("Copyright © Vestindo Certo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/mega-sena-background.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 340));

        setSize(new java.awt.Dimension(409, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        ViewMenuPrincipal viewMenuPrincipal = new ViewMenuPrincipal();
        viewMenuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonAnalisarJogosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnalisarJogosActionPerformed
        //Váriaveis de apoios
        int count = 0, i = 0, controlePlayrer01 = 0, totalPlayer01 = 0;
        int jogo[][] = new int[3][6];
        int matrizSorteios[][] = new int[3000][6];
        String strPlayer01 = "";
        
        //Listas setadas
        List<ControllerRegistros> listaDeRegistros = new ArrayList<ControllerRegistros>();
        List<ControllerSorteios> listaDeSorteios = new ArrayList<ControllerSorteios>();
        
        //Controllers respectivos
        ControllerRegistros registros = new ControllerRegistros();
        ControllerSorteios sorteios = new ControllerSorteios();
        
        //Listas com dados
        listaDeRegistros = registros.getRegistros();
        listaDeSorteios = sorteios.getSorteios();
        
        //Setado jogos de registros
        for (ControllerRegistros registrosLocal : listaDeRegistros) { //Iterator: Para cada carro na list de carros...
            jogo[count][0] = registrosLocal.getDezena01(); 
            jogo[count][1] = registrosLocal.getDezena02();
            jogo[count][2] = registrosLocal.getDezena03();
            jogo[count][3] = registrosLocal.getDezena04();
            jogo[count][4] = registrosLocal.getDezena05();
            jogo[count][5] = registrosLocal.getDezena06();
            count++;
            if(count == 3) break;
        }
        
        //Lista dos sorteios
        count = 0;
        for (ControllerSorteios sorteiosLocal : listaDeSorteios) { //Iterator: Para cada carro na list de carros...
            matrizSorteios[count][0] = sorteiosLocal.getDezena01(); 
            matrizSorteios[count][1] = sorteiosLocal.getDezena02();
            matrizSorteios[count][2] = sorteiosLocal.getDezena03();
            matrizSorteios[count][3] = sorteiosLocal.getDezena04();
            matrizSorteios[count][4] = sorteiosLocal.getDezena05();
            matrizSorteios[count][5] = sorteiosLocal.getDezena06();
            count++;
        }
        
        int countJogadores = 0; String strJogo, resultadoFinal = "";
        for (ControllerRegistros registrosLocal : listaDeRegistros) {
            controlePlayrer01 = 0;
            totalPlayer01 = 0;
            for (i = 0; i < 3000; i++) {
                for (int j = 0; j < 6; j++) {
                    for (int k = 0; k < 6; k++) {
                        if(jogo[countJogadores][j] == matrizSorteios[i][k]){
                            controlePlayrer01++;
                        }
                    }   
                }
                strJogo = (
                        registrosLocal.getDezena01() + " " + 
                        registrosLocal.getDezena02() + " " + 
                        registrosLocal.getDezena03() + " " + 
                        registrosLocal.getDezena04() + " " + 
                        registrosLocal.getDezena05() + " " + 
                        registrosLocal.getDezena06()
                    );
                if(controlePlayrer01 > totalPlayer01){
                    totalPlayer01 = controlePlayrer01;
                    strPlayer01 = "<b>"+registrosLocal.getNome()+" - "+strJogo+"</b>, <blockquote>no jogo " + (i+1) + " você acertou " + totalPlayer01 + " números</blockquote>";
                }
                //resultadoFinal += "<b>" + registrosLocal.getNome() + "</b> <blockquote>" + strJogo + " - No jogo"+(i+1)+" você acertou " + totalPlayer01 + " números</blockquote>";
                controlePlayrer01 = 0;
                //System.out.println("Sorteio "+i+": "+matrizSorteios[i][0] + " | " + matrizSorteios[i][1] + " | " + matrizSorteios[i][2] + " | " + matrizSorteios[i][3] + " | " + matrizSorteios[i][4] + " | " + matrizSorteios[i][05] + " | ");
            }
            resultadoFinal += strPlayer01;
            System.out.println(strPlayer01);
            
            countJogadores++;
            if(countJogadores == 3) break;
        }
        
        jLabelDadosDoBanco.setText("<html><body>"+resultadoFinal+"</body></html>");
    }//GEN-LAST:event_jButtonAnalisarJogosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewResultados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewResultados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnalisarJogos;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDadosDoBanco;
    // End of variables declaration//GEN-END:variables
}
