/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.ControllerSorteios;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;

/**
 *
 * @author internet
 */
public class ViewGerarSorteios extends javax.swing.JFrame {

    /**
     * Creates new form Into
     */
    public ViewGerarSorteios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jToggleButtonVoltar = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListSorteios = new javax.swing.JList<>();
        jToggleButtonGerarSorteios = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("Este é seu simulador de jogos da Mega Sena");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 26));

        jToggleButtonVoltar.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jToggleButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-voltar.png"))); // NOI18N
        jToggleButtonVoltar.setText("Voltar");
        jToggleButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 230, 180, 50));

        jScrollPane1.setViewportView(jListSorteios);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 44, 380, 180));

        jToggleButtonGerarSorteios.setFont(new java.awt.Font("Lucida Sans", 0, 16)); // NOI18N
        jToggleButtonGerarSorteios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/trevo-icone.png"))); // NOI18N
        jToggleButtonGerarSorteios.setText("Gerar Sorteios");
        jToggleButtonGerarSorteios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonGerarSorteiosActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonGerarSorteios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 180, 50));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        jLabel1.setText("Copyright © Vestindo Certo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/mega-sena-background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 420, 340));

        setSize(new java.awt.Dimension(422, 360));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonVoltarActionPerformed
        // TODO add your handling code here:
        ViewMenuPrincipal menuPrincipal = new ViewMenuPrincipal();
        menuPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jToggleButtonVoltarActionPerformed

    private void jToggleButtonGerarSorteiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonGerarSorteiosActionPerformed
        // TODO add your handling code here:
        //ERROR_MESSAGE, PLAIN_MESSAGE, INFORMATION_MESSAGE
        DefaultListModel dml = new DefaultListModel();
        ControllerSorteios sorteios = new ControllerSorteios();
        try {
            dml = sorteios.gerarSorteios();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Algo deu errado, tente novamente", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(ViewGerarSorteios.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            jListSorteios.setModel(dml);
            JOptionPane.showMessageDialog(null, "Lista gerada com sucesso!", null, JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jToggleButtonGerarSorteiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewGerarSorteios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewGerarSorteios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewGerarSorteios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewGerarSorteios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewGerarSorteios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jListSorteios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButtonGerarSorteios;
    private javax.swing.JToggleButton jToggleButtonVoltar;
    // End of variables declaration//GEN-END:variables
}
